---
title: "Project_1"
author: "Sarah Eiben, Michelle Baumgarnter, Deni Hodzic"
date: "`r Sys.Date()`"
output: html_document
---


# CREB family member and cofactor binding in K562 cells

Outline:
- Introduction
- Results
- Methods
- Discussion
- References


## Introduction

CREB is an important element in the cAMP signaling pathway, which is bound to the DNA in its inactive state. CREB is then activated by active catalytic domains and ATP molecules. After conversion, phosphorylated CREB can bind to different cofactors, which stimulates the transcription of targeted genes. Although, we know that various CREB family members exist, only the function of CREB1 is understood in more detail, yet.

The K562 cell line is a human cell line derived from myelogenous leukemia cells. The fact that these cells are cancer cells and therefore immortal cells enables the researchers to analyze and use them for scientific purposes over multiple decades.

In our Group project we aim to find the different binding domains of CREB1, CREB3, CREB3L1 and CREB5. By comparing these which each other and in a further step looking at the interaction with H3K27ac and CREB co-factors (CREBBP, JUN, EP300, HDAC2) at these discovered domains, we eventually hope to understand the function of the individual CREB family members better.

Eventually, all the data necessary for our group project was easily obtainable using the ENCODE-project.

### Disclaimer
The communication between us 3 was rather difficult. It is in no way an excuse for the quality of the project but we would like to mention it because it lead to this version of the project that we are handing in, which could in many ways be improved and is lacking in some areas.

```{r}
sessionInfo()
```